# Generated by Django 4.2.1 on 2023-05-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0005_alter_course_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
    ]
